/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.application;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Surid
 */
public class MenuForClient extends javax.swing.JFrame {

    /**
     * Creates new form MenuForClient
     */
    public MenuForClient() {
        initComponents();
    }
    
    private void balanceCheckActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        BalancePanel BalancePanel=new BalancePanel();
        try {
            BalancePanel.ShowData();
            BalancePanel.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuApplicationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        changeMenu = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        checkBalance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Account");

        changeMenu.setSelected(true);
        changeMenu.setText("Change Info");
        changeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(changeMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Balance");

        checkBalance.setText("Check Balance");
        checkBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceActionPerformed(evt);
            }
        });
        jMenu2.add(checkBalance);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceActionPerformed
        // TODO add your handling code here:
        BalancePanel BalancePanel=new BalancePanel();
        try {
            BalancePanel.ShowData();
            BalancePanel.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuApplicationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkBalanceActionPerformed

    private void changeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMenuActionPerformed
        try {
            // TODO add your handling code here:
            ClientFormFrame form = new ClientFormFrame();
            
            form.showData();
            form.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuForClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem changeMenu;
    private javax.swing.JMenuItem checkBalance;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
